CREATE TABLE [contratos].[contratos] (
    [id_contrato] bigint,
    [id_empleado] bigint,
    [id_tipo_contrato] int,
    [id_estado_contrato] int,
    [fecha_inicio] datetime,
    [fecha_fin] datetime,
    [monto_contrato] decimal,
    [moneda] nvarchar,
    [fecha_firma] datetime,
    [duracion_contrato] int,
    [comentarios] nvarchar,
    [condiciones] nvarchar,
    [id_fuente_reclutamiento] int,
    [id_licencia_laboral] int,
    [id_motivo_baja] int,
    [id_clausula_adicional] int,
    CONSTRAINT [FK__contratos__id_fuente_reclutamiento] FOREIGN KEY ([id_fuente_reclutamiento]) REFERENCES [contratos].[fuente_reclutamiento]([id_fuente_reclutamiento]),
    CONSTRAINT [FK__contratos__moned__22CA2527] FOREIGN KEY ([moneda]) REFERENCES [cfdi_40].[cfdi_40_monedas]([id]),
    CONSTRAINT [FK__contratos__id_ti__1EF99443] FOREIGN KEY ([id_tipo_contrato]) REFERENCES [contratos].[tipos_contratos]([id_tipo_contrato]),
    CONSTRAINT [FK__contratos__id_em__1387E197] FOREIGN KEY ([id_empleado]) REFERENCES [empleados].[empleados]([id_empleado]),
    CONSTRAINT [FK__contratos__id_es__21D600EE] FOREIGN KEY ([id_estado_contrato]) REFERENCES [contratos].[estados_contrato]([id_estado_contrato]),
    PRIMARY KEY ([id_contrato])
);